### ISSUE TITLE
Is not in the npm registry.

### ISSUE THREAD

**Issue by AndreiCinc** [boomerang-io/carbon-addons-boomerang-react#28]
Hi there, I hope you are doing well.

I have this project that I have to clone & run on my machine. When I do _npm install_ --force  I get this error 
`npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@boomerang%2fcarbon-addons-boomerang - Not found
npm ERR! 404
npm ERR! 404  '@boomerang/carbon-addons-boomerang@^2.7.0' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

Do you have an ideea why it`s that? Hope you can help me with that, thank you!

**Comment by timrbula** [comment]
Hey @AndreiCinc sorry for late reply to you here, but the npm org is `@boomerang-io`. Here is the [link to it](https://www.npmjs.com/package/@boomerang-io/carbon-addons-boomerang-react). I have updated the documentation to be correct. I apologize for that having the old package name in there before.
